### ISSUE TITLE
No feed items

### ISSUE THREAD

**Issue by jaredbidlow** [gozman/slack-rss#1]
I simply can't identify the RSS items from this. With Inoreader, I am allowed to subscribe to a channel, but there are no updates to the feed. Anyone have success running this app?

**Comment by pgaudiano** [comment]
Works fine for me. But you have to make sure there are shared links in your feed, otherwise you won't get anything back (other than the channel title). Here is the one I just created: http://pginfomoustest.herokuapp.com/feed/general
